export const plants = [
    { name: "Thyme", category: "Plants for Chefs", daysToMaturity: 90 },
    { name: "Bull's Blood", category: "Plants for Chefs", daysToMaturity: 35 },
    { name: "Green Tatsoi", category: "Plants for Chefs", daysToMaturity: 21 },
    { name: "Green Salanova", category: "Plants for Chefs", daysToMaturity: 55 },
    { name: "Basil", category: "Plants for Chefs", daysToMaturity: 68 },
    { name: "Collard Greens", category: "Plants for Chefs", daysToMaturity: 60 },
    { name: "Celery", category: "Plants for Chefs", daysToMaturity: 75 },
    { name: "Lemon Basil", category: "Plants for Chefs", daysToMaturity: 70 },
    { name: "Yellow Swiss Chard", category: "Plants for Chefs", daysToMaturity: 60 },
    { name: "Green Bok Choy", category: "Plants for Chefs", daysToMaturity: 20 },
    { name: "Sunflower", category: "Plants for Chefs", daysToMaturity: 65 },
    { name: "Perpetual Spinach", category: "Plants for Chefs", daysToMaturity: 40 },
    { name: "Kale Lacinato", category: "Plants for Chefs", daysToMaturity: 65 },
    { name: "Purple Kohlrabi", category: "Plants for Chefs", daysToMaturity: 45 },
    { name: "Breen", category: "Flower Lovers", daysToMaturity: 45 },
    { name: "Bull's Blood", category: "Flower Lovers", daysToMaturity: 35 },
    { name: "Butterhead", category: "Flower Lovers", daysToMaturity: 55 },
    { name: "Pink Celery", category: "Flower Lovers", daysToMaturity: 75 },
    { name: "Red Sorrel", category: "Flower Lovers", daysToMaturity: 60 },
    { name: "Salanova", category: "Flower Lovers", daysToMaturity: 50 },
    { name: "Yellow Chard", category: "Flower Lovers", daysToMaturity: 60 },
    { name: "Bunching Onions", category: "Flower Lovers", daysToMaturity: 50 },
    { name: "Lemon Balm", category: "Flower Lovers", daysToMaturity: 70 },
    { name: "Purple Basil", category: "Flower Lovers", daysToMaturity: 65 },
    { name: "Celosia", category: "Flower Lovers", daysToMaturity: 90 },
    { name: "Snapdragon", category: "Flower Lovers", daysToMaturity: 100 },
    { name: "Stock Flower", category: "Flower Lovers", daysToMaturity: 75 },
    { name: "Sunflower", category: "Flower Lovers", daysToMaturity: 65 },
    { name: "White Petunia", category: "Flower Lovers", daysToMaturity: 80 },
    { name: "Breen", category: "Sad Salad Girlies", daysToMaturity: 45 },
    { name: "Bronze Arrow Lettuce", category: "Sad Salad Girlies", daysToMaturity: 55 },
    { name: "Bull's Blood", category: "Sad Salad Girlies", daysToMaturity: 35 },
    { name: "Butterhead", category: "Sad Salad Girlies", daysToMaturity: 55 },
    { name: "Green Tatsoi", category: "Sad Salad Girlies", daysToMaturity: 21 },
    { name: "Kale", category: "Sad Salad Girlies", daysToMaturity: 65 },
    { name: "Kohlrabi", category: "Sad Salad Girlies", daysToMaturity: 45 },
    { name: "Perpetual Spinach", category: "Sad Salad Girlies", daysToMaturity: 40 },
    { name: "Red Mustard", category: "Sad Salad Girlies", daysToMaturity: 35 },
    { name: "Romaine", category: "Sad Salad Girlies", daysToMaturity: 60 },
    { name: "Salanova", category: "Sad Salad Girlies", daysToMaturity: 50 },
    { name: "Watercress", category: "Sad Salad Girlies", daysToMaturity: 30 },
    { name: "Basil", category: "Sad Salad Girlies", daysToMaturity: 30 },
    { name: "Bunching Onions", category: "Sad Salad Girlies", daysToMaturity: 50 },
    { name: "Cilantro", category: "Sad Salad Girlies", daysToMaturity: 28 },
    { name: "Sunflower", category: "Sad Salad Girlies", daysToMaturity: 65 },
];